import test from 'node:test';
import assert from 'node:assert/strict';
import {
  PRACTICE_AREA, QUERY_ALIASES, buildFormIndex, expandQuery, findReferralForms,
  isConfident, nelTree, rankForms,
} from '../lib/referrals/nel-tree.mjs';
import { nelFormNotFound, nelReferralFormAnswer, referralAnswer } from '../lib/templates/referrals.mjs';
import { forcedTemplate, parseCommand } from '../lib/commands.mjs';
import { SELECTION_SCHEMA } from '../lib/templates/route.mjs';

// The NEL Referral Tree is 533 form names lifted out of a PDF, and the whole
// value of them is that they are the strings staff type into EMIS. So these
// tests are mostly about the data still being what the document said, and about
// the matcher refusing to answer rather than answering loosely: "which form for
// a fit note" has no answer on this tree, and "DAIS Referral Form" is a worse
// outcome than saying so.
//
// The dataset is regenerated by `npm run data:nel-tree`. If that script drifts,
// the exact-name assertions below are what fails.

const tree = nelTree();
const forms = tree.forms;

/* ------------------------------------------------------- the data itself */

test('the dataset is the document: counts, date and shape', () => {
  assert.equal(tree.capturedAt, '2026-06-18');
  assert.equal(forms.length, 533);
  assert.equal(tree.categories.length, 17);
  assert.equal(tree.areas.length, 5);
  assert.equal(tree.opening.length, 5);
  // The article's own URL, so a card can say where the list came from.
  assert.match(tree.source, /^https:\/\/support\.primarycareit\.co\.uk\//);
});

test('every form has a name, a known category and no stray whitespace', () => {
  for (const form of forms) {
    assert.ok(form.name, 'a form with no name');
    assert.equal(form.name, form.name.trim(), `padded name: ${JSON.stringify(form.name)}`);
    assert.ok(!/\s{2,}/.test(form.name), `double space in: ${JSON.stringify(form.name)}`);
    assert.ok(tree.categories.includes(form.category), `unknown category: ${form.category}`);
    for (const area of form.areas) {
      assert.ok(tree.areas.some((a) => a.code === area), `unknown area: ${area}`);
    }
  }
});

// Character for character. These are the names somebody retypes, including the
// oddities: doubled brackets, an em-dash-free hyphen run, PCIT's own missing
// spaces in "BirthBirth ReflectionListening", and a name that is two text items
// in the PDF and was silently truncated to "HRS Referral -" until the parser
// learned to rejoin the label column.
test('form names are verbatim, oddities and all', () => {
  const byName = new Set(forms.map((f) => f.name));
  for (const name of [
    'Pan London Urgent Suspected Skin Cancer Referral Form',
    'Combined Health Check Patient Appointment Invite Letter (Easy Read)(PILOT)',
    'Community Gynaecology (Ivy Centre) Referral Form',
    'Anticipatory syringe pump auth Opioid Naive with CKD B&D and Havering',
    'EBI - Chalazia Removal',
    'Attachment-9-polypharmacy-and-deprescribing-deprescribing-pil-2',
    'Referral form Reframing BirthBirth ReflectionListening Clinic CH',
    'HRS Referral - external agencies',
    'Power Up Lifestyle Intervention Service 5 - 19 years (Hackney Ark)',
    "Carer's Centre Referral TH",
  ]) {
    assert.ok(byName.has(name), `missing or altered: ${JSON.stringify(name)}`);
  }
});

// The tick columns are read by x-coordinate, because flattened text gives the
// ticks in order but not which column each sat in. These rows are the proof: a
// row with two ticks that are NOT the first two columns. Read positionally they
// come out right; read by counting they would come out as CH+NH.
test('availability comes from the tick column, not the tick count', () => {
  const find = (name, category) => forms.find((f) => f.name === name && f.category === category);
  assert.deepEqual(find('Wider determinants of health questionnaire NEL', 'Admin').areas, ['NH', 'WF']);
  assert.deepEqual(find('Cardiology Community Service Referral Form', 'Community (incl. Weight Management)').areas, ['NH', 'WF']);
  assert.deepEqual(find('Barts Health parent information on asthma and wheeze', 'Paeds & Young People').areas, ['NH', 'BHR']);
  // TNW is Newham, Tower Hamlets and Waltham Forest — never City & Hackney.
  for (const form of forms.filter((f) => f.category.startsWith('TNW'))) {
    assert.deepEqual(form.areas, ['NH', 'TH', 'WF'], `TNW row with other areas: ${form.name}`);
  }
});

test('the practice is City & Hackney, and 247 forms are on its tree', () => {
  assert.equal(PRACTICE_AREA, 'CH');
  assert.equal(forms.filter((f) => f.areas.includes('CH')).length, 247);
});

// Five rows in the table carry no tick at all. The document says a form is on
// your tree when it is ticked for your area, so no tick means it is not claimed
// for anybody — least of all for us.
test('a form with no tick is never claimed for this practice', () => {
  const unstated = forms.filter((f) => !f.areas.length);
  assert.equal(unstated.length, 5);
  for (const form of unstated) assert.ok(!form.areas.includes('CH'));
});

/* ----------------------------------------------------------- the matcher */

test('a form is found by the words a receptionist would use', () => {
  const cases = [
    ['suspected skin cancer', 'Pan London Urgent Suspected Skin Cancer Referral Form'],
    ['dexa', 'Dexa Scan Request'],
    ['tongue tie', 'Tongue Tie Referral Form 2021 CH'],
    ['cremation form', 'Cremation form 4 medical certificate'],
    ['gender identity', 'Gender Identity Clinic Referral'],
    ['bowel screening kit', 'National Bowel Screening Kit Replacement Request Form'],
  ];
  for (const [asked, expected] of cases) {
    const found = findReferralForms(asked);
    assert.ok(found.confident, `not confident about "${asked}"`);
    assert.equal(found.matches[0].name, expected);
  }
});

test('the shorthand staff say reaches the form the tree calls something else', () => {
  // "2ww" is how a receptionist says it; the tree says "Urgent Suspected".
  assert.equal(
    findReferralForms('2ww skin').matches[0].name,
    'Pan London Urgent Suspected Skin Cancer Referral Form',
  );
  assert.match(findReferralForms('smear').matches[0].name, /Cervical Screening/);
  assert.match(findReferralForms('coil').matches[0].name, /coil implant/);
});

// An alias that no longer reaches anything is worse than no alias: it silently
// stops helping and nothing says so. Every target has to still match a form.
test('every query alias still reaches at least one form', () => {
  const index = buildFormIndex(forms);
  for (const [pattern, addition] of QUERY_ALIASES) {
    assert.ok(rankForms(index, addition, 3).length, `alias target matches nothing: ${addition} (${pattern})`);
  }
});

test('an alias only ever adds to the query, never replaces it', () => {
  assert.equal(expandQuery('dexa'), 'dexa Dexa Scan');
  assert.equal(expandQuery('tongue tie'), 'tongue tie');
  assert.equal(expandQuery(''), '');
});

test('several forms come back as several, not as a guess', () => {
  const found = findReferralForms('vasectomy');
  assert.equal(found.confident, false);
  assert.ok(found.matches.length >= 2);
  assert.deepEqual(
    found.matches.map((f) => f.name).sort(),
    ['MSI Vasectomy Referral Form', 'Vasectomy Referral Form'],
  );
});

// The shared matcher forgives one missing word, which is right for a contacts
// directory and wrong over 247 form names — it is what made "fit note" answer
// with "DAIS Referral Form".
test('a question the tree has no form for is answered with nothing', () => {
  for (const asked of ['fit note', 'sick note', 'printer toner', 'car park permit', 'staff annual leave']) {
    const found = findReferralForms(asked);
    assert.equal(found.matches.length, 0, `"${asked}" matched ${found.matches[0]?.name}`);
    assert.equal(found.elsewhere.length, 0, `"${asked}" matched elsewhere: ${found.elsewhere[0]?.name}`);
  }
});

test('a form another borough has is named, not hidden', () => {
  const found = findReferralForms('redbridge podiatry');
  assert.equal(found.matches.length, 0);
  assert.equal(found.elsewhere[0].name, 'Redbridge Podiatry Referral Form');
  assert.deepEqual(found.elsewhere[0].areas, ['BHR']);
});

test('asking as another borough finds that borough’s forms', () => {
  const found = findReferralForms("carer's centre", { area: 'TH' });
  assert.ok(found.matches.length);
  assert.ok(found.matches.every((f) => f.areas.includes('TH')));
  assert.equal(found.areaName, 'Tower Hamlets');
});

test('an empty question is not a search', () => {
  for (const asked of ['', '   ', null, undefined]) {
    const found = findReferralForms(asked);
    assert.deepEqual(found.matches, []);
    assert.deepEqual(found.elsewhere, []);
    assert.equal(found.confident, false);
  }
});

// The pure parts, over invented rows — the same shape as
// test/contacts-fuzzy.test.mjs, so the ranking can be reasoned about without
// 533 real names in the way.
test('the ranking works over a handful of invented rows', () => {
  const invented = [
    { name: 'Knee Brace Request Form', category: 'Specialist', areas: ['CH'] },
    { name: 'Knee Physiotherapy Referral Form', category: 'Community', areas: ['CH'] },
    { name: 'Shoulder Injection Referral Form', category: 'Specialist', areas: ['CH'] },
  ];
  const index = buildFormIndex(invented);
  assert.equal(rankForms(index, 'shoulder injection')[0].name, 'Shoulder Injection Referral Form');
  assert.equal(rankForms(index, 'knee').length, 2);
  assert.equal(rankForms(index, 'passport renewal').length, 0);
});

test('confidence needs a clear winner', () => {
  assert.equal(isConfident([], 'anything'), false);
  assert.equal(isConfident([{ name: 'Only One', score: 60 }], 'only one'), true);
  // Named outright, so the runner-up does not matter.
  assert.equal(isConfident([{ name: 'Dexa Scan Request', score: 100 }, { name: 'Other', score: 99 }], 'dexa scan request'), true);
  // Too close to call.
  assert.equal(isConfident([{ name: 'A', score: 100 }, { name: 'B', score: 99 }], 'something'), false);
});

/* ------------------------------------------------------------- the cards */

test('the card names the form verbatim and offers it to copy', () => {
  const card = nelReferralFormAnswer('tongue tie');
  assert.equal(card.title, 'Tongue Tie Referral Form 2021 CH');
  const fields = card.blocks.find((b) => b.type === 'fields');
  const form = fields.items.find((i) => i.label === 'Form');
  assert.equal(form.value, 'Tongue Tie Referral Form 2021 CH');
  assert.equal(form.copy, true);
  // The five steps are the document's, shown rather than described.
  assert.equal(card.blocks.find((b) => b.type === 'steps').items.length, 5);
  // And the card says how old the list is.
  assert.deepEqual(card.source, ['NEL Referral Tree (Primary Care IT), as of 18 June 2026']);
});

test('a shortlist card lists every match verbatim', () => {
  const card = nelReferralFormAnswer('vasectomy');
  const rows = card.blocks.find((b) => b.type === 'table').rows;
  assert.deepEqual(rows.map((r) => r[0]).sort(), ['MSI Vasectomy Referral Form', 'Vasectomy Referral Form']);
});

test('a form we cannot see says whose it is', () => {
  const card = nelReferralFormAnswer('redbridge podiatry');
  assert.match(card.title, /not on this practice’s Referral Tree/);
  const rows = card.blocks.find((b) => b.type === 'table').rows;
  assert.equal(rows[0][0], 'Redbridge Podiatry Referral Form');
  assert.match(rows[0][1], /Barking & Dagenham/);
});

test('nothing on the tree is null, so the caller can fall through', () => {
  assert.equal(nelReferralFormAnswer('printer toner'), null);
  assert.equal(nelReferralFormAnswer(''), null);
});

/* ------------------------------------------------------------ /form */

// Typing the command names the list to search, so a miss is that list saying it
// has nothing — never a model writing plausibly about a form that is not on it.
// That is the entire reason to type /form instead of asking in words.
test('/form is a command, and it claims its own template', () => {
  const parsed = parseCommand('/form suspected skin cancer');
  assert.equal(parsed.command.template, 'referralForm');
  assert.equal(parsed.command.fill, 'lookup');
  assert.equal(parsed.rest, 'suspected skin cancer');
  // The server honours a template only when a command claims it.
  assert.equal(forcedTemplate('referralForm'), 'referralForm');
});

// The router must not be able to choose it: an ordinary question keeps going
// through `referral`, which checks the practice's own material first.
test('the model cannot pick the command-only template', () => {
  const templates = SELECTION_SCHEMA.shape.template._def.values;
  assert.ok(!templates.includes('referralForm'));
  assert.ok(templates.includes('referral'));
});

test('a miss on /form is answered by the tree, not by prose', () => {
  const card = nelFormNotFound('fit note');
  assert.match(card.title, /fit note/);
  assert.match(card.title, /no form by that name/);
  assert.match(card.subtitle, /City & Hackney/);
  // It says which list it searched, and how old that list is.
  assert.deepEqual(card.source, ['NEL Referral Tree (Primary Care IT), as of 18 June 2026']);
  // And points at the path that DOES check the practice's own notes.
  assert.match(JSON.stringify(card.blocks), /without the command/);
});

/* -------------------------------------------------------- the precedence */

// The practice's own material answers a different question — how a referral is
// SENT — and it is the more specific answer, so it has to win. These two guard
// the order in referralAnswer.
test('a referral the practice records beats the tree', () => {
  const card = referralAnswer({ question: 'how do I refer for an ECG', name: 'ECG', pages: [] });
  assert.match(card.subtitle, /email/i);
  assert.ok(!/Referral Tree/.test(JSON.stringify(card.source)));
});

test('a referral the Notebook lists beats the tree', () => {
  // "Wheelchair service referral" is on the tree for City & Hackney. With the
  // practice's own page listing it as emailed, the page is the answer.
  const pages = [{
    docTitle: 'Referrals sent by email',
    text: 'These referrals go by email rather than e-RS:\n- Wheelchair service\n- Dietitian\n',
  }];
  const card = referralAnswer({ question: 'wheelchair referral', name: 'wheelchair', pages });
  assert.match(card.subtitle, /email/i);
  assert.match(JSON.stringify(card.blocks), /Wheelchair service/);
});

test('a referral nobody has recorded now reaches the tree', () => {
  const card = referralAnswer({ question: 'tongue tie referral', name: 'tongue tie', pages: [] });
  assert.equal(card.title, 'Tongue Tie Referral Form 2021 CH');
});

test('a referral nobody has recorded and the tree lacks is still honest', () => {
  const card = referralAnswer({ question: 'printer toner referral', name: 'printer toner', pages: [] });
  assert.match(card.subtitle, /Not recorded/);
});
