// Every commit, and the version it produced.
//
// The versions were not recorded at the time, so the early ones are derived by
// walking the history — which is only possible because every commit subject
// says what kind of change it was. That is the whole reason the Conventional
// Commits rule in CLAUDE.md is worth keeping: it makes the history computable
// rather than merely readable.
//
//   npm run versions          rewrite VERSIONS.md, and check package.json
//   npm run versions -- --check   check only, exit 1 if they disagree
//
// The check is the point. package.json is bumped by hand in the commit that
// earns it; this recomputes what it SHOULD be and says so if the two have
// drifted. A version nobody verifies is a number, not a fact.
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// feat is a new capability, so it moves the minor. Everything else — fix, docs,
// refactor, style, test, perf, chore — moves the patch. A "!" after the type
// means a broken contract and moves the major.
const MINOR = new Set(['feat']);

export function walk(rows) {
  let [maj, min, pat] = [1, 0, 0];
  return rows.map((r, i) => {
    const type = (/^([a-z]+)(\([^)]*\))?(!)?:/.exec(r.subject) || [])[1] || 'chore';
    const breaking = /^[a-z]+(\([^)]*\))?!:/.test(r.subject);
    if (i > 0) {
      if (breaking) { maj += 1; min = 0; pat = 0; }
      else if (MINOR.has(type)) { min += 1; pat = 0; }
      else { pat += 1; }
    }
    return { ...r, type, version: `${maj}.${min}.${pat}` };
  });
}

function history() {
  const raw = execSync('git log --reverse --pretty=format:%h%x00%ad%x00%s --date=short', {
    encoding: 'utf8', cwd: root,
  });
  return raw.split('\n').filter(Boolean).map((line) => {
    const [sha, date, subject] = line.split('\0');
    return { sha, date, subject };
  });
}

function table(rows) {
  return [
    '# Versions',
    '',
    'Every commit, and the version it produced. Newest first.',
    '',
    'The rule is arithmetic, not judgement — see `CLAUDE.md`:',
    '',
    '| Commit type | Moves |',
    '| --- | --- |',
    '| `feat` | the **minor** |',
    '| anything else (`fix`, `docs`, `refactor`, `style`, `test`, `perf`, `chore`) | the **patch** |',
    '| any type with `!` after it — a broken contract | the **major** |',
    '',
    'Regenerated by `npm run versions`, which also checks that `package.json`',
    'agrees with the tip of the history. **The newest commit is missing its own',
    'row** until the next run: this file is written before the commit that',
    'contains it exists. `package.json` is the version that is actually shipped,',
    'and it is bumped by hand in the commit that earns it.',
    '',
    '| Version | Date | Type | Commit | Subject |',
    '| --- | --- | --- | --- | --- |',
    ...[...rows].reverse().map((r) =>
      `| \`${r.version}\` | ${r.date} | ${r.type} | \`${r.sha}\` | ${r.subject.replace(/\|/g, '\\|')} |`),
    '',
  ].join('\n');
}

const rows = walk(history());
const expected = rows[rows.length - 1].version;
const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const checkOnly = process.argv.includes('--check');

if (!checkOnly) {
  fs.writeFileSync(path.join(root, 'VERSIONS.md'), table(rows));
  console.log(`[versions] wrote VERSIONS.md — ${rows.length} commits, newest ${expected}`);
}

// The tip of the history has already been committed, so package.json is
// expected to be AT or ONE AHEAD of it: one ahead is the normal state while the
// bump for the commit being written is staged.
if (pkg.version === expected) {
  console.log(`[versions] package.json is ${pkg.version}, matching the newest commit.`);
} else {
  console.log(`[versions] package.json is ${pkg.version}; the newest commit computes to ${expected}.`);
  console.log('[versions] That is correct only if the bump for the commit being written is staged.');
  if (checkOnly) process.exit(1);
}
