// The NEL Referral Tree, searched by name.
//
// PCIT publish a protocol inside EMIS Web that holds every referral form for
// North East London — 533 of them, grouped by clinical category and then by
// borough. Reception's question is always the same shape: "which form do I use
// for X". Until now the answer to most of them was the "not recorded in the
// practice's notes" card, because the practice's own Notebook covers the
// referrals it sends by email and nothing covered the other four hundred.
//
// WHAT THIS DOES NOT DO. It does not produce the form. The forms live in EMIS
// and this application reads nothing from EMIS. It answers which form to open,
// which category it is under, and whether City & Hackney can see it — which is
// the part staff waste time on, because the tree is a list of 533 things with no
// search box beyond Ctrl+F.
//
// EVERY NAME IS VERBATIM. A form name is a string somebody types into the tree,
// so it is carried through from the source PDF character for character and never
// passed through a model. lib/referrals/nel-tree.data.json is generated by
// scripts/build-nel-referral-tree.mjs; nothing here edits it.
//
// A FORM THE PRACTICE CANNOT SEE IS STILL AN ANSWER. The tree only shows a form
// ticked for your own area, so "Autism Service referral form Part A" exists for
// City & Hackney and "Autism Service Referral TH" does not. Saying "that one is
// Tower Hamlets" beats saying nothing: it stops somebody hunting a menu for a
// button that was never going to be there.
import fs from 'node:fs';
import path from 'node:path';
import { buildIndex, fuzzySearch, normalize, tokenize } from '../lookup/fuzzy.js';

// The practice is in City & Hackney. One constant, so another borough is one
// edit and the data already carries all five.
export const PRACTICE_AREA = 'CH';

const DATA_FILE = path.join(process.cwd(), 'lib', 'referrals', 'nel-tree.data.json');

let cache = null;

/** The dataset, read once. */
export function nelTree() {
  if (!cache) cache = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  return cache;
}

/**
 * What reception says, mapped to words the form names actually use.
 *
 * Deliberately tiny and deliberately one-directional: each entry expands a
 * phrase staff say into words that appear VERBATIM in at least one form name, so
 * it can only ever help a query reach a row that was already there. It never
 * renames a form and never invents a route. `test/nel-referral-tree.test.mjs`
 * asserts every target still matches something, so an entry cannot rot quietly
 * when PCIT republish the list.
 */
export const QUERY_ALIASES = [
  [/\b(2ww|2 ?week ?wait|two ?week ?wait|usc|urgent cancer)\b/gi, 'urgent suspected cancer'],
  [/\bsmear\b/gi, 'cervical screening'],
  [/\b(coil|implant|iucd)\b/gi, 'LARC'],
  [/\bdexa\b/gi, 'Dexa Scan'],
  [/\b(tia|mini ?stroke)\b/gi, 'TIA'],
  [/\b(chest pain|racpc)\b/gi, 'Rapid Access Chest Pain'],
  [/\bpalliative\b/gi, 'Specialist Palliative Care'],
  [/\b(eol|end of life)\b/gi, 'End Of Life'],
  [/\bme\b/gi, 'Chronic Fatigue'],
  [/\bdrug ?and ?alcohol\b/gi, 'substance misuse'],
  [/\bweight ?management\b/gi, 'weight management'],
];

/** The query as written, plus whatever the aliases above add to it. */
export function expandQuery(query) {
  const asked = String(query || '').trim();
  const extra = [];
  for (const [pattern, addition] of QUERY_ALIASES) {
    if (pattern.test(asked)) extra.push(addition);
    pattern.lastIndex = 0;
  }
  return extra.length ? `${asked} ${extra.join(' ')}` : asked;
}

/**
 * The searchable index over a list of forms.
 *
 * Takes the forms explicitly rather than reaching for the dataset, so a test can
 * hand it five invented rows — the same shape as lib/contacts.fuzzy.mjs.
 */
export function buildFormIndex(forms = []) {
  return buildIndex(forms.map((form) => ({
    label: form.name,
    category: form.category,
    form,
  })));
}

/**
 * The score a match has to clear to be worth showing, for a query this long.
 *
 * The shared matcher is tuned for the contacts directory — fifty-odd entries,
 * where a loose hit is better than an empty list. Over 247 form names a loose hit
 * is noise: it lets "fit note", which the tree has no form for at all, come back
 * as "DAIS Referral Form" because one weak token landed somewhere. The matcher
 * forgives one missing word on a multi-word query, which is right for a person's
 * name and wrong here.
 *
 * So the bar rises with the number of words asked for: every word has to be
 * earning its place. One word may match loosely (a substring is how "dermatology"
 * reaches "Community Teledermatology Referral Form", worth 65); two words that
 * between them only match one are the shape of a query about something that is
 * not in the tree.
 *
 * Counted on the words the READER typed, not on what the aliases added, so an
 * alias can only ever help.
 */
const floorFor = (query) => 50 * Math.max(1, tokenize(query).length);

/** Forms ranked against a query. Highest score first, noise removed. */
export function rankForms(index, query, limit = 6) {
  const floor = floorFor(query);
  const hits = fuzzySearch(index, expandQuery(query), limit * 3)
    .filter(({ score }) => score >= floor);
  if (!hits.length) return [];
  // Trim the tail: once a match is less than a third as good as the best one, it
  // is padding a list somebody is reading in a hurry.
  const cut = hits[0].score * 0.33;
  return hits
    .filter(({ score }) => score >= cut)
    .slice(0, limit)
    .map(({ entry, score }) => ({ ...entry.form, score }));
}

const available = (form, area) => (form.areas || []).includes(area);

/**
 * One clear winner, or a shortlist?
 *
 * A form is shown on its own when the query names it outright, or when it is
 * well clear of the runner-up. Otherwise the reader picks from a list — a
 * referral form chosen for somebody by a close-run score is the wrong kind of
 * confident, and "dermatology" genuinely is several forms.
 */
export function isConfident(matches, query) {
  if (!matches.length) return false;
  if (matches.length === 1) return true;
  const asked = normalize(query).replace(/[^a-z0-9]/g, '');
  if (asked && normalize(matches[0].name).replace(/[^a-z0-9]/g, '') === asked) return true;
  return matches[0].score >= matches[1].score * 1.35;
}

/**
 * Find the referral form(s) for what was asked.
 *
 * Searches the area's own forms first. Only when those come back empty does it
 * look at the rest of North East London, and it says so — see the note at the
 * top about why an unavailable form is still worth naming.
 *
 * @returns {{
 *   query: string, area: string, areaName: string,
 *   matches: Array, elsewhere: Array, confident: boolean,
 *   capturedAt: string, source: string, opening: string[]
 * }}
 */
export function findReferralForms(query, { area = PRACTICE_AREA, limit = 6, tree = null } = {}) {
  const data = tree || nelTree();
  const asked = String(query || '').trim();
  const areaName = (data.areas.find((a) => a.code === area) || {}).name || area;
  const empty = {
    query: asked, area, areaName, matches: [], elsewhere: [], confident: false,
    capturedAt: data.capturedAt, source: data.source, opening: data.opening,
  };
  if (!asked) return empty;

  const mine = data.forms.filter((f) => available(f, area));
  const matches = rankForms(buildFormIndex(mine), asked, limit);
  if (matches.length) {
    return { ...empty, matches, confident: isConfident(matches, asked) };
  }

  // Nothing on this practice's tree. Is it somebody else's form, or does it not
  // exist at all? The forms with no tick in any column live here too: the list
  // does not say who can see them, so they are never claimed as ours.
  const theirs = data.forms.filter((f) => !available(f, area));
  return { ...empty, elsewhere: rankForms(buildFormIndex(theirs), asked, limit) };
}

/** Which of the five areas can see a form, by full name. */
export function areaNamesFor(form, tree = null) {
  const data = tree || nelTree();
  return (form.areas || []).map((code) => (data.areas.find((a) => a.code === code) || {}).name || code);
}
