// The NEL Referral Tree, searched by name.
//
// PCIT publish a protocol inside EMIS Web that holds every referral form for
// North East London — 533 of them, grouped by clinical category and then by
// borough. Reception's question is always the same shape: "which form do I use
// for X". Until now the answer to most of them was the "not recorded in the
// practice's notes" card, because the practice's own Notebook covers the
// referrals it sends by email and nothing covered the other four hundred.
//
// WHAT THIS DOES NOT DO. It does not produce the form. The forms live in EMIS
// and this application reads nothing from EMIS. It answers which form to open,
// which category it is under, and whether City & Hackney can see it — which is
// the part staff waste time on, because the tree is a list of 533 things with no
// search box beyond Ctrl+F.
//
// EVERY NAME IS VERBATIM. A form name is a string somebody types into the tree,
// so it is carried through from the source PDF character for character and never
// passed through a model. lib/referrals/nel-tree.data.json is generated by
// scripts/build-nel-referral-tree.mjs; nothing here edits it.
//
// A FORM THE PRACTICE CANNOT SEE IS STILL AN ANSWER. The tree only shows a form
// ticked for your own area, so "Autism Service referral form Part A" exists for
// City & Hackney and "Autism Service Referral TH" does not. Saying "that one is
// Tower Hamlets" beats saying nothing: it stops somebody hunting a menu for a
// button that was never going to be there.
// IMPORTED, NOT READ OFF DISK, and it has to stay that way. Everything in
// lib/templates renders in the browser as well as on the server — /templates is a
// client page that renders every card as a sample — so this module is part of a
// browser bundle, and `node:fs` in a browser bundle fails the build outright. An
// import attribute is understood by both webpack and `node --test`.
import DATA from './nel-tree.data.json' with { type: 'json' };
import { buildIndex, fuzzySearch, normalize, tokenize } from '../lookup/fuzzy.js';
import { askedFor } from './ask.mjs';

// The practice is in City & Hackney. One constant, so another borough is one
// edit and the data already carries all five.
export const PRACTICE_AREA = 'CH';

/** The dataset. */
export function nelTree() {
  return DATA;
}

/**
 * What reception says, mapped to words the form names actually use.
 *
 * Deliberately tiny and deliberately one-directional: each entry expands a
 * phrase staff say into words that appear VERBATIM in at least one form name, so
 * it can only ever help a query reach a row that was already there. It never
 * renames a form and never invents a route. `test/nel-referral-tree.test.mjs`
 * asserts every target still matches something, so an entry cannot rot quietly
 * when PCIT republish the list.
 */
export const QUERY_ALIASES = [
  [/\b(2ww|2 ?week ?wait|two ?week ?wait|usc|urgent cancer)\b/gi, 'urgent suspected cancer'],
  [/\bsmear\b/gi, 'cervical screening'],
  [/\b(coil|implant|iucd)\b/gi, 'LARC'],
  [/\bdexa\b/gi, 'Dexa Scan'],
  [/\b(tia|mini ?stroke)\b/gi, 'TIA'],
  [/\b(hearing|deaf|hard of hearing)\b/gi, 'Audiology'],
  [/\b(chest pain|racpc)\b/gi, 'Rapid Access Chest Pain'],
  [/\bpalliative\b/gi, 'Specialist Palliative Care'],
  [/\b(eol|end of life)\b/gi, 'End Of Life'],
  [/\bme\b/gi, 'Chronic Fatigue'],
  [/\bdrug ?and ?alcohol\b/gi, 'substance misuse'],
  [/\bweight ?management\b/gi, 'weight management'],
];

/** The query as written, plus whatever the aliases above add to it. */
export function expandQuery(query) {
  const asked = String(query || '').trim();
  const extra = [];
  for (const [pattern, addition] of QUERY_ALIASES) {
    if (pattern.test(asked)) extra.push(addition);
    pattern.lastIndex = 0;
  }
  return extra.length ? `${asked} ${extra.join(' ')}` : asked;
}

/**
 * The searchable index over a list of forms.
 *
 * Takes the forms explicitly rather than reaching for the dataset, so a test can
 * hand it five invented rows — the same shape as lib/contacts.fuzzy.mjs.
 */
export function buildFormIndex(forms = []) {
  return buildIndex(forms.map((form) => ({
    label: form.name,
    category: form.category,
    form,
  })));
}

/**
 * The score a match has to clear to be worth showing, for a query this long.
 *
 * The shared matcher is tuned for the contacts directory — fifty-odd entries,
 * where a loose hit is better than an empty list. Over 247 form names a loose hit
 * is noise: it lets "fit note", which the tree has no form for at all, come back
 * as "DAIS Referral Form" because one weak token landed somewhere. The matcher
 * forgives one missing word on a multi-word query, which is right for a person's
 * name and wrong here.
 *
 * So the bar rises with the number of words asked for: every word has to be
 * earning its place. One word may match loosely (a substring is how "dermatology"
 * reaches "Community Teledermatology Referral Form", worth 65); two words that
 * between them only match one are the shape of a query about something that is
 * not in the tree.
 *
 * Counted on the words the READER typed, not on what the aliases added, so an
 * alias can only ever help.
 *
 * AND NOT ON THE WORDS THAT DID THE ASKING. "which form do I use for adhd" is
 * six words about one, and counting the five that name nothing put the bar at
 * 300 for an answer worth 108 — see lib/referrals/ask.mjs. The bar is counted
 * on what was asked FOR.
 */
const floorFor = (query) => 50 * Math.max(1, tokenize(askedFor(query)).length);

/**
 * What a match has to score to be worth showing ON ITS OWN, with no hedge.
 *
 * Roughly "every word the reader typed found its word in the name". Below it the
 * form is still the best thing on the tree and still worth showing — it is just
 * not something to put in front of somebody as the answer. That distinction is
 * the whole of it: "bloods" scored 60 and came back as a confident, copyable
 * "24 Hour Blood Pressure Monitoring Request Form", and "derm" scored 98 and
 * came back as "Derman Referral Form", which is a community organisation and
 * has nothing to do with dermatology.
 */
const strongFor = (query) => 100 * Math.max(1, tokenize(askedFor(query)).length);

/**
 * Is this row a form to send, or a piece of paper to hand over?
 *
 * The tree carries both. "Talking Therapies Referral Information" is a leaflet
 * and "Asthma Stop smoking support letter" is a letter for a patient, and both
 * were beating the actual referral forms for the same words — a leaflet won
 * "talking therapies" outright, and the asthma letter won "stop smoking" over
 * "Smoking Cessation Service Referral Form". Somebody who typed /form wants the
 * form.
 */
const HANDOUT = /\b(letter|leaflet|checklist|script|information|toolkit|invite|guidance)\b/i;
const isHandout = (form) =>
  form.category === 'NEL Information documents to print' || HANDOUT.test(form.name);

/**
 * Forms ranked against a query. Highest score first, noise removed.
 *
 * The floor is applied to the BEST match only, deciding whether there is an
 * answer here at all. It used to be applied to every row, which quietly hid the
 * right answers: "stop smoking" kept "Asthma Stop smoking support letter" at 200
 * and dropped "Smoking Cessation Service Referral Form" at 60, because that one
 * matched only one of the two words.
 */
export function rankForms(index, query, limit = 6) {
  // A handout is pushed below the forms unless the reader asked for one. Scored
  // rather than filtered: when a handout is genuinely all there is — "housing
  // letter" — it is still the answer.
  const wantsHandout = HANDOUT.test(String(query || ''));
  // Searched on what was asked FOR. The asking words are dropped first because
  // "referral" and "form" are in almost every name on this tree: they match
  // everything, so they rank nothing, and they were only ever raising the bar.
  const raw = fuzzySearch(index, expandQuery(askedFor(query)), limit * 3);
  // WHETHER THERE IS AN ANSWER AT ALL is judged on the undemoted scores. Judging
  // it after the demotion made things disappear: "stop smoking" has a real form
  // on this tree, but once the asthma letter was pushed down, the best remaining
  // score fell under the floor and the card said the tree had nothing — which
  // was true of neither.
  if (!raw.length || raw[0].score < floorFor(query)) return [];
  const hits = raw
    .map(({ entry, score }) => ({
      entry, score: !wantsHandout && isHandout(entry.form) ? Math.round(score * 0.35) : score,
    }))
    .sort((a, b) => b.score - a.score || a.entry.label.length - b.entry.label.length);
  // Once past that, keep anything in the same league as the best — a quarter of
  // it — so a weaker row that is the better answer still gets to be seen.
  const cut = Math.max(45, hits[0].score * 0.25);
  return hits
    .filter(({ score }) => score >= cut)
    .slice(0, limit)
    .map(({ entry, score }) => ({ ...entry.form, score }));
}

const available = (form, area) => (form.areas || []).includes(area);

/**
 * One clear winner, or a shortlist?
 *
 * A form is shown on its own when the query names it outright, or when it is
 * well clear of the runner-up. Otherwise the reader picks from a list — a
 * referral form chosen for somebody by a close-run score is the wrong kind of
 * confident, and "dermatology" genuinely is several forms.
 */
/**
 * Was this row named outright, rather than described?
 *
 * The query is compared both as typed and with the asking words dropped, so
 * "Dexa Scan Request" and "which Dexa Scan Request form" both count. THE ROW'S
 * NAME IS NEVER TRIMMED, and that asymmetry is load-bearing: nearly every row on
 * this tree ends "Referral Form", so trimming the row would turn one clinical
 * word into an outright naming of it — "vasectomy" would have named "Vasectomy
 * Referral Form" outright and hidden "MSI Vasectomy Referral Form", which is a
 * real second answer and the reason the shortlist exists.
 */
const flat = (s) => normalize(s).replace(/[^a-z0-9]/g, '');
export function namedOutright(name, query) {
  const row = flat(name);
  if (!row) return false;
  return [flat(query), flat(askedFor(query))].filter(Boolean).includes(row);
}

export function isConfident(matches, query) {
  if (!matches.length) return false;
  // The form named outright. Nothing else needs checking.
  //
  // Compared BOTH ways round — as typed, and with the asking words dropped from
  // each side — because either can be the one that matches. "Dexa Scan Request"
  // typed in full is the name as written; "the dexa scan form" is the same form
  // named outright in English, and both are the reader saying which row they
  // mean rather than describing a symptom.
  if (namedOutright(matches[0].name, query)) return true;
  // BEING THE ONLY MATCH IS NOT THE SAME AS BEING A GOOD ONE, and treating it as
  // such is what produced every wrong card the trial found: one weak survivor of
  // the ranking became a single, unhedged, copyable answer. Strength first, then
  // clear water.
  if (matches[0].score < strongFor(query)) return false;
  if (matches.length === 1) return true;
  return matches[0].score >= matches[1].score * 1.35;
}

/**
 * The best the tree can do, but not good enough to state flatly.
 *
 * One match, and it did not clear the bar. Worth showing — it is still the
 * closest thing on the tree — but the card has to say that rather than present
 * it as the form.
 */
export const isTentative = (matches, query) =>
  matches.length === 1 && !isConfident(matches, query);

/**
 * Find the referral form(s) for what was asked.
 *
 * Searches the area's own forms first. Only when those come back empty does it
 * look at the rest of North East London, and it says so — see the note at the
 * top about why an unavailable form is still worth naming.
 *
 * @returns {{
 *   query: string, area: string, areaName: string,
 *   matches: Array, elsewhere: Array, confident: boolean,
 *   capturedAt: string, source: string, opening: string[]
 * }}
 */
export function findReferralForms(query, { area = PRACTICE_AREA, limit = 6, tree = null } = {}) {
  const data = tree || nelTree();
  const asked = String(query || '').trim();
  const areaName = (data.areas.find((a) => a.code === area) || {}).name || area;
  const empty = {
    query: asked, area, areaName, matches: [], elsewhere: [], confident: false, tentative: false,
    capturedAt: data.capturedAt, source: data.source, opening: data.opening,
  };
  if (!asked) return empty;

  const mine = data.forms.filter((f) => available(f, area));
  const matches = rankForms(buildFormIndex(mine), asked, limit);
  if (matches.length) {
    return {
      ...empty,
      matches,
      confident: isConfident(matches, asked),
      tentative: isTentative(matches, asked),
    };
  }

  // Nothing on this practice's tree. Is it somebody else's form, or does it not
  // exist at all? The forms with no tick in any column live here too: the list
  // does not say who can see them, so they are never claimed as ours.
  const theirs = data.forms.filter((f) => !available(f, area));
  return { ...empty, elsewhere: rankForms(buildFormIndex(theirs), asked, limit) };
}

/** Which of the five areas can see a form, by full name. */
export function areaNamesFor(form, tree = null) {
  const data = tree || nelTree();
  return (form.areas || []).map((code) => (data.areas.find((a) => a.code === code) || {}).name || code);
}
